DROP TABLE IF EXISTS MOVIES CASCADE;
DROP TABLE IF EXISTS PERSONS CASCADE;
DROP TABLE IF EXISTS COORDINATES CASCADE;
DROP TABLE IF EXISTS LOCATIONS CASCADE;

DROP TYPE IF EXISTS MpaaRating CASCADE;
DROP TYPE IF EXISTS MovieGenre CASCADE;
DROP TYPE IF EXISTS Color CASCADE;
DROP TYPE IF EXISTS Country CASCADE;
